### DISCUSSION TITLE
How does port checking work internally?

### DISCUSSION THREAD

**Discussion by Pierric82** [transmission/transmission#6652] [Q&A]
Hi,

I'm wondering how port checking works internally, since I'm struggling with getting a proper set up working with VPN port forwarding (for background, using Proton VPN, whereby I have a VM running Debian connected to Proton via wireguard, with PMP port mapping enabled; transmission is running on another machine, as a container, using a macvlan network access whereby the Proton-connected VM is acting as its gateway; this setup works overall for other containers, but my other containers don't require port forwarding).

Here's the thing: I can successfully create a port forward with Proton. When I "connect" this onto transmission, using socat (I relay tcp and udp traffic coming in from the Proton port to the same port that Proton picked on the transmission IP), I can use sites like portchecker.co to confirm the port is open (which really means socat is getting the connection; using `-d` `-d` on socat shows me that this connection is picked up properly). But if I then configure transmission to use that same port, it tells me after a few seconds that the port is closed. _After this, checking using portchecker.co no longer works!_ That is, until I rerun natpmpc which seems to "refresh" the port forwarding. This sequence happens no matter how fast the sequence happens and is therefore not linked to the lifetime of the port forward. Checking the port from transmission somehow temporarily breaks the port forward on Proton side.

I've asked Proton support for their input on this, but in order to understand better, **I'd like to know exactly what transmission does when it checks if the port is open**. I had understood earlier that it just calls canyouseemenow.org from the backend, but I'm not sure anymore. Can someone explain this to me? I've also tried to check the source code to find out but got lost in the process.

For reference I'm illustrating here the kind of setup I'm aiming for, but really my core question for now is: how does the port checking work? if I understand this better I might be able to investigate more efficiently.

<img width="350" alt="image" src="https://github.com/transmission/transmission/assets/58935627/1df53e8e-d3ce-4343-8bb3-6fabb671fae0">

Thanks in advance!
P.

**Comment by tearfur** [comment]
When Transmission does a port check, it simply calls a port checking service similar to canyouseeme.org using curl. All we do is specify the destination url, and other curl settings for an easy handle, then we leave everything to curl.

If you want to know what those curl settings are, you can look at `tr_web::Impl::initEasy()` in `libtransmission/web.cc`.

> But if I then configure transmission to use that same port, it tells me after a few seconds that the port is closed. _After this, checking using portchecker.co no longer works!_ That is, until I rerun natpmpc which seems to "refresh" the port forwarding.

That's weird. Although I can't see how it can be related atm, we do have some port forwarding code in serveral files named `libtransmission/port-forwarding*`. *And* we have been getting issue reports about problems with that part of the code here and there.

**Reply by Pierric82** [reply]
Thanks for a very considerate and helpful answer!

I've been looking at `web.cc` and `port-forwarding.cc` but didn't find the actual details of which service is being called (as in concrete URL, get/post, body/parameters etc.) - I feel a bit stupid admitting this because I suppose it's got to be somewhere!

> we do have some port forwarding code

With my approach, in principle, I shouldn't be triggering that code since I'm handling the port forwarding externally and just informing transmission about which port to use and letting it confirm whether it's open or not. Unless there's some unwanted interference from the port forwarding code, but I wouldn't call this likely...

**Reply by tearfur** [reply]
The destination url is here:

https://github.com/transmission/transmission/blob/1855cdb7312acf903d37e0bb3a66501c2042fc44/libtransmission/rpcimpl.cc#L1168-L1175

You should get a pretty good idea of what's going on if you chase down the call stack of the `session->fetch()` function call near the end of `portTest()`.

**Reply by Pierric82** [reply]
Thanks!

This is very interesting.

First interesting thing: I ran `curl https://portcheck.transmissionbt.com/46562` (this being the latest port assigned by natpmpc) from the VM running the VPN gateway, and I get '1'. Running the same command from inside the transmission container gets me a '0' (after a longer time). The public IP is the same for both, which I confirmed with `curl ifconfig.me`, so they should be looking at the same thing...

Second interesting thing: with this approach, running the transmission check (i.e. curling transmissionbt.com) does NOT "break" the port forwarding like when I use the web front-end to run the check. I can switch go to portchecker.co again after running the curl command from inside the container, and portchecker.co will still confirm the port is open.

Now if you have any ideas about what this could mean, I'll be reading them with high interest, because this whole thing completely baffles me! I have not yet "chased down the call stack" used in the code, but will try to do so, if my meagre skills allow for it. I suppose there must be something explaining the "breaking" of my port forwarding via the UI; but the sheer fact that the curl command returns something different when run inside the transmission container is also a hint I need to make sense of.

**Reply by tearfur** [reply]
I haven't got an idea either, but as I said, we specify some custom curl options in `tr_web::Impl::initEasy()`. So maybe you can add the command line equivalent of each of those options to your curl tests one by one, and find out which one breaks it.

**Reply by Pierric82** [reply]
Hi again @tearfur ,

Thanks to your help, I've solved my issue! It turned out - as always - to be a rather mundane mistake. My gateway machine acting as relay between the VPN and the transmission container was only doing masquerading one way. I got the idea to check the NAT setup after thinking some more about the fact that the same curl command yielded different results from the 2 machines, even though the publicly visible IP was the same. To be honest, I still don't fully understand why this difference is there. In my mind, once the transmissionbt.com server receives my curl query, it checks the IP from the caller and tries to connect on the port from the URL. This connection attempt is in my mind independent from the incoming HTTP query, and should not be affected by where the curl command originated from in my internal network 🤔 But in any case, after thinking "maybe I should not restrict masquerading to that interface only", it started working.

I would not have solved it without your help understanding how transmission queries its website; I would probably have given up due to my lack of visibility on what was happening. So I really want to thank you from the bottom of my heart for dedicating some time to answering me!

**Reply by tearfur** [reply]
...Maybe Transmission was just binded to a different interface than what your command line curl was using? Wouldn't that explain everything?

**Reply by Pierric82** [reply]
Hmm... I'm not sure... I don't think the container had many interesting alternatives and I can't wrap my head around why it would cause the observed behaviour... but the more I think about it, the more my brain melts :D  I suppose I ought to build a sandbox scenario bit by bit to understand when the failure happens. If I get time, I'm sure I'll learn a ton by doing that!

**Reply by mrjay42** [reply]
> Hi again @tearfur ,
> 
> Thanks to your help, I've solved my issue! It turned out - as always - to be a rather mundane mistake. My gateway machine acting as relay between the VPN and the transmission container was only doing masquerading one way. I got the idea to check the NAT setup after thinking some more about the fact that the same curl command yielded different results from the 2 machines, even though the publicly visible IP was the same. To be honest, I still don't fully understand why this difference is there. In my mind, once the transmissionbt.com server receives my curl query, it checks the IP from the caller and tries to connect on the port from the URL. This connection attempt is in my mind independent from the incoming HTTP query, and should not be affected by where the curl command originated from in my internal network 🤔 But in any case, after thinking "maybe I should not restrict masquerading to that interface only", it started working.
> 
> I would not have solved it without your help understanding how transmission queries its website; I would probably have given up due to my lack of visibility on what was happening. So I really want to thank you from the bottom of my heart for dedicating some time to answering me!

Hey,

I'm trying to achieve the same thing
And I was wondering if you would be ok in sharing your stack? Like, how did you setup the whole thing?

Thank you in advance ^^

**Reply by Pierric82** [reply]
Hi @mrjay42 ,
I can, but I'll need to go look for it and clean it up a bit. It involves an obscene set of badly written scripts, that infinitely loop to keep the port forward alive and update transmission when a port change is detected. I'm not sure when I'll get a chance to have a look, but ping me if you see no answer by next week.

**Reply by Pierric82** [reply]
I've actually managed to have a quick go at it today, it's not the most explicit text in the world, but hopefully that will help understand my setup. 

Keep in mind it's not a compose stack because I use ansible to deploy my containers, and it's part of a long set of config files for many different containers. But I've captured the important bits (in ansible format, easily translated to docker compose) that make this particular setup work. 

Or sort of work. I struggled for the longest time with socat commands being spawned with the previous ones still alive, and today doing this I realised it was broken silently (though the file I'm sharing has the solution already worked in). 

Hope that helps!

[Keeping port forwarding alive for transmission with a Proton VPN gateway.md](https://github.com/user-attachments/files/26288256/Keeping.port.forwarding.alive.for.transmission.with.a.Proton.VPN.gateway.md)

**Reply by mrjay42** [reply]
> I've actually managed to have a quick go at it today, it's not the most explicit text in the world, but hopefully that will help understand my setup.
> 
> Keep in mind it's not a compose stack because I use ansible to deploy my containers, and it's part of a long set of config files for many different containers. But I've captured the important bits (in ansible format, easily translated to docker compose) that make this particular setup work.
> 
> Or sort of work. I struggled for the longest time with socat commands being spawned with the previous ones still alive, and today doing this I realised it was broken silently (though the file I'm sharing has the solution already worked in).
> 
> Hope that helps!
> 
> [Keeping port forwarding alive for transmission with a Proton VPN gateway.md](https://github.com/user-attachments/files/26288256/Keeping.port.forwarding.alive.for.transmission.with.a.Proton.VPN.gateway.md)

Omg thank you so much <3 <3

**Reply by lagraviereScience** [reply]
> I've actually managed to have a quick go at it today, it's not the most explicit text in the world, but hopefully that will help understand my setup.
> 
> Keep in mind it's not a compose stack because I use ansible to deploy my containers, and it's part of a long set of config files for many different containers. But I've captured the important bits (in ansible format, easily translated to docker compose) that make this particular setup work.
> 
> Or sort of work. I struggled for the longest time with socat commands being spawned with the previous ones still alive, and today doing this I realised it was broken silently (though the file I'm sharing has the solution already worked in).
> 
> Hope that helps!
> 
> [Keeping port forwarding alive for transmission with a Proton VPN gateway.md](https://github.com/user-attachments/files/26288256/Keeping.port.forwarding.alive.for.transmission.with.a.Proton.VPN.gateway.md)

I found a stack that works perfectly with: Traefik + Docker Compose + ProtonVPN + Port Forwarding + Transmission, here it is:
```yml
# ======================================================================================
# COMMUNITY STACK: GLUETUN (PROTONVPN WITH NAT-PMP) + TRANSMISSION TORRENT CLIENT
# ARCHITECTURE: Transmission shares Gluetun's network namespace (All traffic via VPN).
# AUTOMATION: Dynamic port changes are caught by Gluetun and pushed to Transmission RPC.
# ======================================================================================

services:
  gluetun-proton:
    image: qmcgaw/gluetun:latest
    container_name: gluetun-proton
    # NET_ADMIN capability is mandatory for Gluetun to manipulate routing tables and firewall rules
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      - private_secured_network

    environment:
      - TZ=UTC # Change to your timezone (e.g., Europe/Paris, America/New_York)
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      
      # --- PROTONVPN NAT-PMP CONFIGURATION ---
      # Tells Gluetun to request an open incoming peer port via NAT-PMP protocols
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_PROVIDER=protonvpn
      
      # --- LOCAL FIREWALL BYPASS RULES ---
      # Adjust to your local physical LAN layout to ensure you can access the web UI locally
      - FIREWALL_OUTBOUND_SUBNETS=192.168.1.0/24
      # Exposes Transmission's Web UI/RPC port inside Gluetun's firewall layer
      - FIREWALL_INPUT_PORTS=9091

      # --- GLUETUN HEALTH CONTROL SERVER ---
      - HTTP_CONTROL_SERVER=on
      - HTTP_CONTROL_SERVER_PORT=9999

      # --- THE AUTOMATION HOOK (THE BRAINS) ---
      # When the tunnel goes UP and Proton grants a port, this command fires instantly.
      # 1. Installs 'transmission-remote' natively within Gluetun's lightweight Alpine base.
      # 2. Uses template variable {{PORTS}} (Gluetun auto-substitutes this with the real port number).
      # 3. Connects via localhost (since network namespaces are shared) to inject the peer port.
      # 4. Forces an immediate reannounce on all active torrents to broadcast the open port to peers.
      # NOTE: Ensure the '-n user:pass' arguments match the USER and PASS environment values below.
      - VPN_PORT_FORWARDING_UP_COMMAND=/bin/sh -c "apk add --no-cache transmission-remote && transmission-remote localhost:9091 -n YOUR_RPC_USERNAME:YOUR_RPC_PASSWORD -p {{PORTS}} && transmission-remote localhost:9091 -n YOUR_RPC_USERNAME:YOUR_RPC_PASSWORD -t all --reannounce"

    volumes:
      # Mount your custom ProtonVPN WireGuard config file (Ensure 'Port Forwarding' is checked in Proton Dashboard)
      - /path/to/your/apps/vpnProton/wg0.conf:/gluetun/wireguard/wg0.conf:ro
      # Dynamic state storage for Gluetun container
      - gluetun-proton-state:/gluetun

    # --- TRAEFIK REVERSE PROXY LABELS ---
    # Routed directly off the gluetun container because Transmission shares its network interface.
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=private_secured_network"
      # Change your entrypoints, resolvers, and domain hosts to fit your production infrastructure
      - "traefik.http.routers.transmission-proton.rule=Host(`torrents.example.com`)"
      - "traefik.http.routers.transmission-proton.entrypoints=websecure"
      - "traefik.http.routers.transmission-proton.tls.certresolver=yourresolver"
      - "traefik.http.services.transmission-proton.loadbalancer.server.port=9091"

    healthcheck:
      test: ["CMD", "nc", "-z", "127.0.0.1", "9999"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 10s

  transmission-proton:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission-proton
    restart: unless-stopped

    # --- THE SECURE BUBBLE CRITICAL SETTING ---
    # Tells Docker to place Transmission completely inside Gluetun's network space.
    # It will have no independent IP, ensuring zero traffic can bypass the VPN tunnel.
    network_mode: "service:gluetun-proton"

    # Keeps the container from executing until Gluetun verifies its tunnel health check is active
    depends_on:
      gluetun-proton:
        condition: service_healthy

    environment:
      - PUID=1000 # Modify to your host user's UID to prevent file permission issues
      - PGID=1000 # Modify to your host user's GID to prevent file permission issues
      - TZ=UTC    # Match with your system timezone
      - USER=YOUR_RPC_USERNAME # Secure login for WebUI/RPC (Must match Hook command above)
      - PASS=YOUR_RPC_PASSWORD # Secure password for WebUI/RPC (Must match Hook command above)

    volumes:
      # Application runtime configuration data
      - /path/to/your/apps/vpnProton/transmission-config:/config
      
      # Persistent Storage Volumes (Map to your host infrastructure media folders)
      - /path/to/your/storage/downloads/completed:/downloads/completed
      - /path/to/your/storage/downloads/incomplete:/downloads/incomplete
      - /path/to/your/storage/downloads/torrents:/downloads/torrents
      - /path/to/your/storage/downloads/watch:/watch
      
      # Example Media sub-category bindings (Uncomment or adapt to add media types)
      # - /path/to/your/storage/media/movies:/downloads/completed/movies
      # - /path/to/your/storage/media/tv:/downloads/completed/tv
      # - /path/to/your/storage/media/audiobooks:/downloads/completed/audiobooks

# --- EXTERNAL NETWORK REQUIREMENT ---
# Uses the pre-existing external network where your Traefik proxy is deployed.
networks:
  private_secured_network:
    external: true

# --- LOCAL NAMED VOLUMES ---
volumes:
  # Isolated named volume keeping Gluetun state information persistent between image updates
  gluetun-proton-state:
```

I also posted it here https://github.com/lagraviereScience/perfectStacks/blob/main/protonVPN/docker-compose.yml
