### DISCUSSION TITLE
transmission-daemon on Ubuntu 24.04 LTS or 24.10 on Docker fails to respect ENV variable: TRANSMISSION_WEB_HOME

### DISCUSSION THREAD

**Discussion by btbutts** [transmission/transmission#8439] [Support]
### What is the issue?

Environmental Details:
I know there's already a composed docker image of transmission on the Docker Hub but I decided to build my own on Docker so I could customize the image a bit further. Currently, I've built my Dockerfile config with Ubuntu 24.04 LTS and 24.10 base images, installing minimal packages, including transmission-daemon, transmission-common, & transmission-cli based on the Ubuntu wiki page. I can configure the transmission-daemon perfectly fine, and launch and stop it using the default debian-transmission user via:
`sudo -H -u debian-transmission /usr/bin/bash -c "service transmission-daemon [ start | stop | status ]"`

I have not enabled _Privileged Mode_ for the container but I have allocated a TTY and enabled interactive processes <docker run -it>. This means that my container has not booted with systemctl via systemd \@PID1, thus I can't use systemctl to start, stop, and reconfigure the transmission-daemon IE:`systemctl edit transmission-daemon.service`.

What is the issue?
I would like to leverage the TRANSMISSION_WEB_HOME environment variable so that I can use 3rd party Web UI's. I fully understand that you all can't support those 3rd party UI's, but the variable itself should still work to override the source path transmission loads the web files from. Whilst the container is running in the config I described above, I tried setting the variable globally via /etc/profile with `TRANSMISSION_WEB_HOME=/var/web/transmission/flood-for-transmission/` but that didn't work. I tried editing the following transmission-daemon.service files via the [Service] section too (one at a time):
+ /etc/systemd/system/multi-user.target.wants/transmission-daemon.service
+ /usr/lib/systemd/system/transmission-daemon.service

However, neither of those config files worked. I also tried adding a modification to init.d via:
+ /etc/init.d/transmission-daemon

However, that also did not work. No matter where I specified the TRANSMISSION_WEB_HOME ENV Variable, the transmission-daemon returned its default web UI via its RPC port. This somewhat differs from the documentation too, which states that if this specific ENV Variable is called, but whose value is blank, the web RPC will fail to load. Whereas, I had called the variable in several places, not all at once, but it did not do anything at all. And yes, I restarted the transmission-daemon after each modification, and I also checked to ensure that the variable remained after transmission had started up again.

I decided to try it with systemd loaded at container boot next by executing `exec /sbin/init` via my Dockerfile's ENTRYPOINT argument. With systemd started, the variable worked. Then I reverted the changes since I don't want my transmission container to run with elevated privileges. Since I confirmed that the transmission docker container can run the 3rd paryt UI when loaded with systemd, that confirms that the UI I want to use works so I sym-linked the contents of the 3rd party UI to the absolute path of the transmission default web UI.

After restarting transmission-daemon, I loaded the new UI just fine via the WEB-RPC port.  That also worked perfectly and immediately. This tells me that transmission-daemon can work with a 3rd party UI in a docker container running without systemd. The issue is, it just won't respect the variables as you all have defined in your documentation here:
https://github.com/transmission/transmission/blob/main/docs/Environment-Variables.md

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.6

**Comment by pid1** [comment]
Post your Dockerfile and how you're starting it.

It doesn't sound like you're actually providing that environment variable anywhere that the container would pick it up.

What happens if you provide the env var via docker run -e TRANSMISSION_WEB_HOME=foo?

**Comment by killemov** [comment]
Setting `TRANSMISSION_WEB_HOME` in the docker environment should work. Do mind any configured volumes which take precedence. So if you have configured:
```dockerfile
volumes:
      - /opt/transmission:/config
``` 
and:
```dockerfile
environment:
      - TRANSMISSION_WEB_HOME=/config/shift
``` 
Then the actual directory of the web interface would be `/opt/transmission/shift`.

**Comment by btbutts** [comment]
I took some time off from this project. Sorry for the delay. I had already added an ENV line in my Dockerfile though. There's actually a whole section for this where I create the directory the alternative webUI will be stored, set permissions, etc...

However, since simply adding the ENV TRANSMISSION_WEB_HOME=/var/web/transmission/flood-for-transmission/ wasn't working as expected, the last few lines of that section run a script that links the `/var/web/transmission/flood-for-transmission/` directory to the default `/usr/share/transmission/public_html/` path.

I've got a few things commented out intentionally as I'm still building the dockerfile for some other aspects of this image.

Also, I do have a volume mounted from the host this container runs on, but that volume is not in, within, or a part of the $TRANSMISSION_WEB_HOME. That mounted volume is in `/mnt` and performed via my compose file. I've copied my compose.yaml underneath my dockerfile.


## Dockerfile

```
## A few prereqs...#
FROM ubuntu:24.10 AS ubuntu-base
ARG RELEASE
ARG LAUNCHPAD_BUILD_ARCH
ARG TARGETPLATFORM
ARG TARGETARCH
LABEL org.opencontainers.image.ref.name="ubuntu-with-sshd-transmission"
LABEL org.opencontainers.image.version="transmission-v24.10"
LABEL org.opencontainers.image.description="Ubuntu 24.10 with SSH-Server & Transmission4"
LABEL org.opencontainers.image.vendor="Clarksville-Lab"
ADD ubuntu-*-oci-$LAUNCHPAD_BUILD_ARCH-root.tar.gz /
SHELL ["/bin/bash", "-o", "pipefail", "-c"]


## Setup the default sytem user account
#RUN useradd -rm -d /home/ubuntu -s /bin/bash -g root -G sudo ubuntu
RUN echo 'ubuntu:password' | chpasswd
USER ubuntu
WORKDIR /home/ubuntu


# Build image with SSHD label
FROM ubuntu-base AS ubuntu-with-sshd
USER root

## Install Additional Software
RUN apt update && apt install -y man-db net-tools vim bash-completion command-not-found
RUN apt update && apt install -y network-manager netplan.io netstat-nat 
RUN apt update && apt install -y locales nano htop build-essential ca-certificates \
        curl git man wget unzip software-properties-common speedtest-cli python3 python3-venv \
        openssh-server openssh-client sudo iputils-ping jq \ 
        transmission-cli transmission-common transmission-daemon bind9-dnsutils zip gzip tar \ 
        systemd systemd-container systemd-resolved bc iputils-arping dumb-init \
        #systemd-standalone-sysusers systemd-sysv \
        #wireguard-tools wireguard \ 
        dbus dbus-user-session uidmap kmod iproute2 iptables libcap-ng-utils \
        && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
ENV LANG=en_US.utf8
## Upgrade Packages
RUN apt update && apt -y upgrade


## Add Docker Keyring, Repository, and install Docker packages
#RUN install -m 0755 -d /etc/apt/keyrings
#RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
#RUN chmod a+r /etc/apt/keyrings/docker.asc
#RUN echo \
#        "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
#        $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
#RUN apt update
#RUN apt -y install docker-ce-rootless-extras


# Init Systemd globally via /etc/profile
RUN printf "systemctl start systemd-logind" >> /etc/profile

## Add 2nd User tadmin
USER root
RUN useradd -rm -d /home/tadmin -s /bin/bash -g root -G sudo tadmin
RUN echo 'tadmin:password' | chpasswd
RUN echo 'tadmin:password' | chpasswd
RUN set -xe usermod -aG sudo tadmin

## Prepare and Preconfigure Users and Transmission
RUN systemctl enable transmission-daemon
RUN service transmission-daemon start
RUN service transmission-daemon stop
RUN gpasswd --add debian-transmission ubuntu && gpasswd --add tadmin ubuntu
RUN usermod -a -G debian-transmission root
RUN usermod -a -G debian-transmission tadmin
RUN usermod -a -G debian-transmission ubuntu
RUN touch /var/log/transmission-daemon.log
RUN chmod 664 /var/log/transmission-daemon.log
RUN chown root:debian-transmission /var/log/transmission-daemon.log
RUN mkdir -p /root/scripts
COPY config-scripts/DockerUbuntuTransmissionConfig.sh /root/scripts
COPY config-scripts/EnableTransmissionLogger.sh /root/scripts
WORKDIR /root/scripts
RUN chmod +x /root/scripts/DockerUbuntuTransmissionConfig.sh
RUN chmod +x /root/scripts/EnableTransmissionLogger.sh
RUN ./EnableTransmissionLogger.sh

## docker-systemctl-replacement script
## This GitHub repo will replace the default systemctl process
## with a pythong script aimed at serving similar functionality
## but for the limited docker container environment.
## More details can be found at the URL below:
## https://github.com/gdraheim/docker-systemctl-replacement/tree/master
#######################################################################
#COPY extra/systemctl-replacement/files/docker/systemctl3.py /usr/bin/systemctl
#RUN chmod +x /usr/bin/systemctl

## Init DBUS Config
RUN dbus-uuidgen > /var/lib/dbus/machine-id
RUN mkdir -p /var/run/dbus
COPY config-scripts/dbus-run.sh /root/scripts
RUN chmod +x /root/scripts/dbus-run.sh
ENV DBUS_SESSION_BUS_ADDRESS="unix:path=/var/run/dbus/system_bus_socket"

## Add User Shell Customizations
COPY config-scripts/ConfigureShell.sh /root/scripts
RUN chmod +x /root/scripts/ConfigureShell.sh
WORKDIR /root/scripts
RUN ./ConfigureShell.sh

## Add Init systemctl boot script
COPY config-scripts/systemctl-sysInit.sh /root/scripts
RUN chmod +x /root/scripts/systemctl-sysInit.sh

## Setup Transmission 3rd Party WebUI Flood for Transmission
## https://github.com/johman10/flood-for-transmission?tab=readme-ov-file#flood-for-transmission
ENV TRANSMISSION_WEB_HOME=/var/web/transmission/flood-for-transmission/
RUN mkdir -p /var/web/transmission/flood-for-transmission
RUN chmod -R 775 /var/web
COPY --chown=debian-transmission:debian-transmission --chmod=764 extra/flood-for-transmission-master/ /var/web/transmission/flood-for-transmission/
RUN chown -R debian-transmission:debian-transmission /var/web
RUN chmod -R 775 /var/web
RUN find /var/web -type f -exec chmod 764 {} \;
COPY config-scripts/Enable-FloodForTransmission.sh /root/scripts
RUN chmod +x /root/scripts/Enable-FloodForTransmission.sh
RUN ./Enable-FloodForTransmission.sh


## Configure SSH and Generate User Keys
WORKDIR /home/ubuntu
RUN ssh-keygen -A -v
RUN update-rc.d ssh defaults
USER ubuntu
RUN ssh-keygen -t ed25519 -f ~/.ssh/id_ed25519
USER tadmin
WORKDIR /home/tadmin
RUN ssh-keygen -t ed25519 -f ~/.ssh/id_ed25519

##expose TCP_22
EXPOSE 22/tcp

##Entrypoint
USER root
WORKDIR /root
ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["bash", "-c", "/root/scripts/dbus-run.sh && /root/scripts/DockerUbuntuTransmissionConfig.sh" ]
```

## compose.yaml

```
version: '3'
##Begin Container Config##
services:
  ubuntu-transmission:
    container_name: Transmission-onUbuntu #app_name: transmission4ubuntu
    image: btbutts/ubuntu-base-sshd:transmission-v24.10-dumb-init
    build:
      context: .
      labels:
        org.opencontainers.image.ref.name: "ubuntu-with-sshd-transmission"
        org.opencontainers.image.version: "transmission-v24.10"
        org.opencontainers.image.description: "Ubuntu 24.10 with SSH-Server & Transmission4"
    networks:
      vl.110-servers:
        ipv4_address: 10.1.10.182
      pia-wireguard-lan:
        ipv4_address: 10.255.255.30
    dns:
      - 1.1.1.1
      - 9.9.9.9
    hostname: ubuntu4transmission
    environment:
      - DBUS_SESSION_BUS_ADDRESS="unix:path=/var/run/dbus/system_bus_socket"
      - TRANSMISSION_WEB_HOME=/var/web/transmission/flood-for-transmission/
    #deploy:
    #  restart_policy:
    #    condition: on-failure
    #    delay: 5s
    #    max_attempts: 2
    #    window: 180s
    restart: 'no'
    volumes:
      - /share/Multimedia:/mnt/QNAPmultimedia:rw
    stdin_open: true    # docker run -i
    tty: true           # docker run -t


##Global Services Config##
networks:
  vl.110-servers:
    name: vl.110-servers
    driver: qnet
    driver_opts:
      iface: "eth0.110"
    ipam:
      driver: qnet
      options:
        iface: "eth0.110"
      config:
        - subnet: 10.1.10.0/24
          gateway: 10.1.10.1
  pia-wireguard-lan:
    name: pia-wireguard-lan
    external: true
```
