### ISSUE TITLE
transmission-daemon never starts the download - stuck on retrieving metadata

### ISSUE THREAD

**Issue by maretodoric** [transmission/transmission#1618]
Hello everyone,

running transmission-daemon (v3.00-1) on centos 8 core. When i add the torrent (magnet link) it cannot start download and sits like that for days. Message displayed in torrent (Magnetized transfer - retrieving metadata (0.00%)).
I tried with or without DHT (on PC when i download torrents it usually works better without DHT for some reason, but on PC always works, not on CentOS) and there are no results.

Bellow is settings.json file

```
{
    "alt-speed-down": 50,
    "alt-speed-enabled": false,
    "alt-speed-time-begin": 540,
    "alt-speed-time-day": 127,
    "alt-speed-time-enabled": false,
    "alt-speed-time-end": 1020,
    "alt-speed-up": 50,
    "bind-address-ipv4": "127.0.0.1",
    "bind-address-ipv6": "::",
    "blocklist-enabled": false,
    "blocklist-url": "http://www.example.com/blocklist",
    "cache-size-mb": 4,
    "dht-enabled": false,
    "download-dir": "/mnt/2TB/media/Nepogledani",
    "download-queue-enabled": true,
    "download-queue-size": 5,
    "encryption": 1,
    "idle-seeding-limit": 30,
    "idle-seeding-limit-enabled": false,
    "incomplete-dir": "/root/Downloads",
    "incomplete-dir-enabled": false,
    "lpd-enabled": false,
    "message-level": 1,
    "peer-congestion-algorithm": "",
    "peer-id-ttl-hours": 6,
    "peer-limit-global": 200,
    "peer-limit-per-torrent": 50,
    "peer-port": 51413,
    "peer-port-random-high": 65535,
    "peer-port-random-low": 49152,
    "peer-port-random-on-start": false,
    "peer-socket-tos": "default",
    "pex-enabled": true,
    "port-forwarding-enabled": true,
    "preallocation": 1,
    "prefetch-enabled": true,
    "queue-stalled-enabled": true,
    "queue-stalled-minutes": 30,
    "ratio-limit": 2,
    "ratio-limit-enabled": false,
    "rename-partial-files": true,
    "rpc-authentication-required": false,
    "rpc-bind-address": "127.0.0.1",
    "rpc-enabled": true,
    "rpc-host-whitelist": "127.0.0.1",
    "rpc-host-whitelist-enabled": true,
    "rpc-password": "{17abde8706e4555624e63a30a5a7ff536d0cfd84QdZXfLht",
    "rpc-port": 9091,
    "rpc-url": "/transmission/",
    "rpc-username": "",
    "rpc-whitelist": "127.0.0.1,::1",
    "rpc-whitelist-enabled": true,
    "scrape-paused-torrents-enabled": true,
    "script-torrent-done-enabled": false,
    "script-torrent-done-filename": "",
    "seed-queue-enabled": false,
    "seed-queue-size": 10,
    "speed-limit-down": 100,
    "speed-limit-down-enabled": false,
    "speed-limit-up": 100,
    "speed-limit-up-enabled": false,
    "start-added-torrents": true,
    "trash-original-torrent-files": false,
    "umask": 18,
    "upload-slots-per-torrent": 14,
    "utp-enabled": true
}
```

I would appreciate help on getting this resolved. Torrents are not blocked in my ISP, works fine on PC. Also, CentOS doesn't have firewalld running (and selinux disabled) so nothing to block it from OS side.

**Comment by jeroen7s** [comment]
Same Issue here, any fixes?

**Comment by berkaey** [comment]
same here - macOS Monterey 12.0.1 MBP M1

**Comment by ProIcons** [comment]
bump

**Comment by maretodoric** [comment]
Not sure what the problem is when running from package, really, but this works flawlessly in Docker...
https://hub.docker.com/r/linuxserver/transmission

My docker-compose.yaml

```
version: "2.1"
services:
  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=Europe/Belgrade
      - USER=admin #optional
      - PASS=password #optional
    volumes:
      - /mnt/2TB/media/transmission/config:/config
      - /mnt/2TB/media/transmission/downloads:/downloads
      - /mnt/2TB/media/transmission/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
```

Change parameters as needed. PUID and PGID will likely be same in your environment.
