### ISSUE TITLE
Transmission wrong download location

### ISSUE THREAD

**Issue by Compr0mzd** [transmission/transmission#6218]
### What is the issue?

I'm trying to download a torrent using a CIFS folder mounted on the host and the transmission docker.
In my docker compose I have the driver as : 
```
media-stack-torrents:
    driver: local
    driver_opts: 
      o: bind
      type: none
      device: /mnt/storage
```
```
transmission:
    depends_on:
    - vpn
    container_name: transmission
    image: linuxserver/transmission:latest
    network_mode: service:vpn
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
      - USER=${TRANSMISSION_USERNAME}
      - PASS=${TRANSMISSION_PASSWORD}
    volumes:
      - tx-config:/config
      - media-stack-torrents:/downloads
      - tx-watch:/watch
    restart: "unless-stopped"
```
On the host there is my fstab entry
```
//FQDN/backup/docker/media-stack  /mnt/storage cifs credentials=/root/.smb 0        0
```
When I cd inside the /mnt/storage I get the correct path which is "/backup/docker/media-stack" however when I download any torrents using transmission web. It makes them download inside "/backup" which is the root path of the CIFS share instead of the path "/backup/docker/media-stack".
I tried changing the path inside transmission without any success. Could it be a perms problem or it could be related to transmission itself ? 

Thanks in advance

### Which application of Transmission?

Web client

### Which version of Transmission?

4.0.4
