### ISSUE TITLE
Transmission Won't Run Script When Done Downloading

### ISSUE THREAD

**Issue by nyxs** [transmission/transmission#6303]
### What is the issue?

I'm using a docker environment.

docker-compose has the following environment variables:
```YAML
volumes:
      - /opt/transmission-container/config:/config
      - /opt/transmission-container/scripts:/scripts
environment:
      - TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED=true
      - TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME="/scripts/afterDL.sh"
````
I've updated the /config/settings.json from the host (/opt/transmission-container/config/settings.json) and set:
      "script-torrent-done-enabled": true,
      "script-torrent-done-filename": "/scripts/afterDL.sh",
I validated the update of the settings.json with these values by looking into the /config/settings.json file inside the docker.

I've set the afterDL.sh file with `chmod +x` from within the docker.

The first thing written in the script is:
```bash
echo -e "TR_TORRENT_DIR: ${TR_TORRENT_DIR}\nTR_TORRENT_NAME: ${TR_TORRENT_NAME}\nTR_TORRENT_ID: ${TR_TORRENT_ID}" > /proc/1/fd/1
```

Nothing of this works.
I can run the script manually and I see the output when I open the docker's logs using:
```bash
sudo docker logs -f transmission
```
But when a download is done, and it starts seeding already, nothing works.

I noticed that when I performed:
```bash
sudo docker compose restart transmission
```
The settings.json files, both on the host and inside the docker, are resetting the "script-torrent-done-enabled" and the "script-torrent-done-filename" settings.

What am I doing wrong?

Thanks.

### Which application of Transmission?

Web client

### Which version of Transmission?

4.0.4 24077e3511
